'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { addWeeks, parseISODate, toISODate, WEEK_DISPLAY_ORDER } from '@/lib/weeks'

export type AddShiftErrorCode = 'errorMissingFields' | 'errorStartBeforeEnd' | 'errorGeneric'

export type AddShiftState = {
  status: 'idle' | 'success' | 'error'
  errorCode?: AddShiftErrorCode
}

export async function addShift(
  _prevState: AddShiftState,
  formData: FormData
): Promise<AddShiftState> {
  const weekStartDate = formData.get('weekStartDate')
  const dayOfWeekValues = formData
    .getAll('dayOfWeek')
    .filter((v): v is string => typeof v === 'string' && v.length > 0)
  const startTime = formData.get('startTime')
  const endTime = formData.get('endTime')
  const label = formData.get('label')
  const capacity = formData.get('capacity')
  const functionId = formData.get('functionId')

  if (
    typeof weekStartDate !== 'string' ||
    typeof startTime !== 'string' ||
    typeof endTime !== 'string' ||
    typeof label !== 'string' ||
    typeof capacity !== 'string' ||
    typeof functionId !== 'string' ||
    !weekStartDate ||
    dayOfWeekValues.length === 0 ||
    !startTime ||
    !endTime ||
    !label.trim() ||
    !capacity ||
    !functionId
  ) {
    return { status: 'error', errorCode: 'errorMissingFields' }
  }

  if (startTime >= endTime) {
    return { status: 'error', errorCode: 'errorStartBeforeEnd' }
  }

  const supabase = await createClient()
  // One shifts_template row per selected day — same time/name/capacity/
  // function on each, matching how a single-day add already worked.
  const { data: inserted, error } = await supabase
    .from('shifts_template')
    .insert(
      dayOfWeekValues.map((dayOfWeek) => ({
        week_start_date: weekStartDate,
        day_of_week: Number(dayOfWeek),
        start_time: startTime,
        end_time: endTime,
        shift_name: label.trim(),
        capacity: Number(capacity),
        function_id: functionId,
      }))
    )
    .select('id')

  if (error || !inserted || inserted.length === 0) {
    return { status: 'error', errorCode: 'errorGeneric' }
  }

  await Promise.all(
    inserted.map((row) => reconcileRosterSlots(supabase, weekStartDate, row.id, Number(capacity)))
  )

  revalidatePath('/manager/schedule')
  return { status: 'success' }
}

// A draft roster's roster_shifts rows are otherwise only (re)generated by a
// full Auto-plan run — without this, a shift added, or capacity-changed,
// after the last Auto-plan run would be out of sync: too few roster_shifts
// rows and the grid falls back to a bare '—' instead of an assignment
// dropdown (slotsByShift.get(shift.id) in page.tsx), too many and a removed
// slot's employee lingers assigned in the database despite being invisible
// (page.tsx only renders slotIndex < shift.capacity).
//
// Reconciles against the *actual* roster_shifts row count for this shift,
// not a before/after capacity delta — a delta assumes the row count already
// matched the old capacity, which isn't true for a shift that predates this
// function (or drifted out of sync any other way); counting what's actually
// there is self-healing regardless of history. Prefers deleting unassigned
// slots first when shrinking, only falling back to an assigned one (cleanly
// unassigning that employee) once there aren't enough empty slots left to
// absorb the reduction. No-op once the roster is published, matching the
// lock enforced elsewhere for Auto-plan and the assignment dropdowns.
async function reconcileRosterSlots(
  supabase: Awaited<ReturnType<typeof createClient>>,
  weekStartDate: string,
  shiftTemplateId: string,
  targetCapacity: number
) {
  const { data: roster } = await supabase
    .from('roster')
    .select('id, is_published')
    .eq('week_start_date', weekStartDate)
    .maybeSingle()

  if (!roster || roster.is_published) return

  const { data: slots } = await supabase
    .from('roster_shifts')
    .select('id, employee_id')
    .eq('shift_template_id', shiftTemplateId)

  const current = slots ?? []

  if (current.length < targetCapacity) {
    const rows = Array.from({ length: targetCapacity - current.length }, () => ({
      roster_id: roster.id,
      shift_template_id: shiftTemplateId,
      employee_id: null,
    }))
    const { error } = await supabase.from('roster_shifts').insert(rows)
    if (error) console.error('reconcileRosterSlots insert failed:', error)
  } else if (current.length > targetCapacity) {
    const idsToRemove = [...current]
      .sort((a, b) => (a.employee_id ? 1 : 0) - (b.employee_id ? 1 : 0))
      .slice(0, current.length - targetCapacity)
      .map((s) => s.id)
    const { error } = await supabase.from('roster_shifts').delete().in('id', idsToRemove)
    if (error) console.error('reconcileRosterSlots delete failed:', error)
  }
}

export type ShiftSnapshot = {
  id: string
  week_start_date: string
  day_of_week: number
  start_time: string
  end_time: string
  shift_name: string
  capacity: number
  function_id: string
  // roster_shifts cascade-deletes with the shift template (see initial_schema
  // migration: shift_template_id ... on delete cascade) — captured here so
  // Undo can restore not just the shift but who was assigned to each of its
  // capacity slots, not just an empty shift.
  rosterShifts: { roster_id: string; employee_id: string | null }[]
}

// Returns a full snapshot of the deleted shift (including its roster_shifts
// assignments, about to be cascade-deleted) so the caller can offer Undo —
// see restoreShift, which reinserts exactly this snapshot.
export async function deleteShift(id: string): Promise<ShiftSnapshot | null> {
  const supabase = await createClient()

  const { data: shift } = await supabase
    .from('shifts_template')
    .select('id, week_start_date, day_of_week, start_time, end_time, shift_name, capacity, function_id')
    .eq('id', id)
    .maybeSingle()

  if (!shift) return null

  const { data: rosterShifts } = await supabase
    .from('roster_shifts')
    .select('roster_id, employee_id')
    .eq('shift_template_id', id)

  const { error } = await supabase.from('shifts_template').delete().eq('id', id)
  if (error) {
    console.error('deleteShift failed:', error)
    return null
  }

  revalidatePath('/manager/schedule')
  return { ...shift, rosterShifts: rosterShifts ?? [] }
}

export type RestoreShiftResult = { status: 'success' } | { status: 'error' }

// Undo for deleteShift: reinserts the shift template with its original id
// (free again since it was just deleted) and re-creates one roster_shifts
// row per captured slot with its original employee_id, so an assigned shift
// comes back assigned rather than just as an empty slot.
export async function restoreShift(snapshot: ShiftSnapshot): Promise<RestoreShiftResult> {
  const supabase = await createClient()

  const { error: shiftError } = await supabase.from('shifts_template').insert({
    id: snapshot.id,
    week_start_date: snapshot.week_start_date,
    day_of_week: snapshot.day_of_week,
    start_time: snapshot.start_time,
    end_time: snapshot.end_time,
    shift_name: snapshot.shift_name,
    capacity: snapshot.capacity,
    function_id: snapshot.function_id,
  })

  if (shiftError) {
    console.error('restoreShift failed to reinsert shift:', shiftError)
    return { status: 'error' }
  }

  if (snapshot.rosterShifts.length > 0) {
    const { error: slotsError } = await supabase.from('roster_shifts').insert(
      snapshot.rosterShifts.map((slot) => ({
        roster_id: slot.roster_id,
        shift_template_id: snapshot.id,
        employee_id: slot.employee_id,
      }))
    )
    if (slotsError) console.error('restoreShift failed to reinsert roster_shifts:', slotsError)
  }

  revalidatePath('/manager/schedule')
  return { status: 'success' }
}

export type UpdateShiftResult = { status: 'success' } | { status: 'error' }

export async function updateShift(
  shiftId: string,
  input: { shiftName: string; startTime: string; endTime: string; capacity: number }
): Promise<UpdateShiftResult> {
  const supabase = await createClient()

  const { data: existing } = await supabase
    .from('shifts_template')
    .select('week_start_date')
    .eq('id', shiftId)
    .maybeSingle()

  const { error } = await supabase
    .from('shifts_template')
    .update({
      shift_name: input.shiftName,
      start_time: input.startTime,
      end_time: input.endTime,
      capacity: input.capacity,
    })
    .eq('id', shiftId)

  if (error) {
    console.error('updateShift failed:', error)
    return { status: 'error' }
  }

  if (existing) {
    await reconcileRosterSlots(supabase, existing.week_start_date, shiftId, input.capacity)
  }

  revalidatePath('/manager/schedule')
  return { status: 'success' }
}

export type RenameShiftGroupResult = { status: 'success' } | { status: 'error' }

// Renames every shifts_template row in the group at once (e.g. all the days
// "od" occurs on) — the grid's row label represents the whole group, not
// any single day, so that's what clicking it should rename.
export async function renameShiftGroup(
  shiftIds: string[],
  name: string
): Promise<RenameShiftGroupResult> {
  const supabase = await createClient()
  const { error } = await supabase.from('shifts_template').update({ shift_name: name }).in('id', shiftIds)

  if (error) {
    console.error('renameShiftGroup failed:', error)
    return { status: 'error' }
  }

  revalidatePath('/manager/schedule')
  return { status: 'success' }
}

export async function copyPreviousWeek(weekStartDate: string) {
  const supabase = await createClient()
  const prevWeek = toISODate(addWeeks(parseISODate(weekStartDate), -1))

  const { count } = await supabase
    .from('shifts_template')
    .select('id', { count: 'exact', head: true })
    .eq('week_start_date', weekStartDate)

  // Safety: never duplicate into a week that already has shifts.
  if (count && count > 0) {
    return
  }

  const { data: prevShifts } = await supabase
    .from('shifts_template')
    .select('day_of_week, start_time, end_time, shift_name, capacity, function_id')
    .eq('week_start_date', prevWeek)

  if (!prevShifts || prevShifts.length === 0) {
    return
  }

  await supabase.from('shifts_template').insert(
    prevShifts.map((s) => ({
      week_start_date: weekStartDate,
      day_of_week: s.day_of_week,
      start_time: s.start_time,
      end_time: s.end_time,
      shift_name: s.shift_name,
      capacity: s.capacity,
      function_id: s.function_id,
    }))
  )

  revalidatePath('/manager/schedule')
}

export type CopyMode = 'merge' | 'overwrite'

export type CopyToWeekErrorCode =
  | 'errorNoShiftsToCopy'
  | 'errorNoWeeksSelected'
  | 'errorAllTargetsPublished'
  | 'errorGeneric'

export type CopyToWeekState = {
  status: 'idle' | 'success' | 'error'
  errorCode?: CopyToWeekErrorCode
  copiedCount?: number
  skippedCount?: number
}

type SourceShift = {
  day_of_week: number
  start_time: string
  end_time: string
  shift_name: string
  capacity: number
  function_id: string
}

// Merge matches on what a shift *is* (function, day, time), not its label or
// headcount — a manager may have renamed or resized it in the target week
// without wanting a copy to duplicate it.
function shiftMatchKey(s: { function_id: string; day_of_week: number; start_time: string; end_time: string }) {
  return `${s.function_id}::${s.day_of_week}::${s.start_time}::${s.end_time}`
}

// Forward-direction sibling of copyPreviousWeek: copies the currently-viewed
// week's shifts into one or more weeks the manager picks, instead of only
// pulling the previous week into an empty current one. Unlike
// copyPreviousWeek (which only ever targets an empty week), a target week
// here may already have shifts, so the manager picks how to handle that per
// copy: 'merge' (default) only adds shifts that don't already exist there;
// 'overwrite' deletes the target week's existing shifts_template rows first
// (cascading to roster_shifts, so any draft assignments on them go too).
export async function copyShiftsToWeek(
  sourceWeekStartDate: string,
  _prevState: CopyToWeekState,
  formData: FormData
): Promise<CopyToWeekState> {
  const targetWeeks = formData.getAll('targetWeek').filter((v): v is string => typeof v === 'string' && v.length > 0)
  const mode: CopyMode = formData.get('copyMode') === 'overwrite' ? 'overwrite' : 'merge'

  if (targetWeeks.length === 0) {
    return { status: 'error', errorCode: 'errorNoWeeksSelected' }
  }

  const supabase = await createClient()

  const { data: sourceShifts } = await supabase
    .from('shifts_template')
    .select('day_of_week, start_time, end_time, shift_name, capacity, function_id')
    .eq('week_start_date', sourceWeekStartDate)
    .returns<SourceShift[]>()

  if (!sourceShifts || sourceShifts.length === 0) {
    return { status: 'error', errorCode: 'errorNoShiftsToCopy' }
  }

  // A published week is locked, same as Auto-plan and the assignment
  // dropdowns elsewhere — never silently rewrite or add to a live schedule.
  const { data: rosters } = await supabase
    .from('roster')
    .select('week_start_date, is_published')
    .in('week_start_date', targetWeeks)

  const publishedWeeks = new Set((rosters ?? []).filter((r) => r.is_published).map((r) => r.week_start_date))
  const writableWeeks = targetWeeks.filter((w) => !publishedWeeks.has(w))

  if (writableWeeks.length === 0) {
    return { status: 'error', errorCode: 'errorAllTargetsPublished' }
  }

  const { data: existingRows } = await supabase
    .from('shifts_template')
    .select('id, week_start_date, day_of_week, start_time, end_time, function_id')
    .in('week_start_date', writableWeeks)

  const existingByWeek = new Map<string, { id: string; day_of_week: number; start_time: string; end_time: string; function_id: string }[]>()
  for (const row of existingRows ?? []) {
    const list = existingByWeek.get(row.week_start_date) ?? []
    list.push(row)
    existingByWeek.set(row.week_start_date, list)
  }

  let copiedCount = 0
  let skippedCount = sourceShifts.length * (targetWeeks.length - writableWeeks.length)
  const idsToDelete: string[] = []
  const insertRows: (SourceShift & { week_start_date: string })[] = []

  for (const week of writableWeeks) {
    const existingForWeek = existingByWeek.get(week) ?? []
    if (mode === 'overwrite') {
      idsToDelete.push(...existingForWeek.map((r) => r.id))
      for (const s of sourceShifts) {
        insertRows.push({ ...s, week_start_date: week })
        copiedCount++
      }
    } else {
      const existingKeys = new Set(existingForWeek.map(shiftMatchKey))
      for (const s of sourceShifts) {
        if (existingKeys.has(shiftMatchKey(s))) {
          skippedCount++
        } else {
          insertRows.push({ ...s, week_start_date: week })
          copiedCount++
        }
      }
    }
  }

  if (idsToDelete.length > 0) {
    const { error: deleteError } = await supabase.from('shifts_template').delete().in('id', idsToDelete)
    if (deleteError) {
      console.error('copyShiftsToWeek delete failed:', deleteError)
      return { status: 'error', errorCode: 'errorGeneric' }
    }
  }

  const { data: insertedRows, error: insertError } = await supabase
    .from('shifts_template')
    .insert(insertRows)
    .select('id, week_start_date, capacity')

  if (insertError) {
    console.error('copyShiftsToWeek insert failed:', insertError)
    return { status: 'error', errorCode: 'errorGeneric' }
  }

  // Immediately give newly-copied shifts an assignment dropdown if their
  // week already has a draft roster — otherwise they'd show a bare '—'
  // until the next Auto-plan run, the same gap fixed for addShift/
  // updateShift via reconcileRosterSlots. Done as one bulk pass here rather
  // than calling reconcileRosterSlots per row, since every inserted row is
  // guaranteed to start at 0 existing roster_shifts.
  const weeksWithInserts = [...new Set((insertedRows ?? []).map((r) => r.week_start_date))]
  if (weeksWithInserts.length > 0) {
    const { data: rostersForWeeks } = await supabase
      .from('roster')
      .select('id, week_start_date')
      .in('week_start_date', weeksWithInserts)

    const rosterIdByWeek = new Map((rostersForWeeks ?? []).map((r) => [r.week_start_date, r.id]))

    const slotRows = (insertedRows ?? []).flatMap((row) => {
      const rosterId = rosterIdByWeek.get(row.week_start_date)
      if (!rosterId) return []
      return Array.from({ length: row.capacity }, () => ({
        roster_id: rosterId,
        shift_template_id: row.id,
        employee_id: null,
      }))
    })

    if (slotRows.length > 0) {
      const { error: slotsError } = await supabase.from('roster_shifts').insert(slotRows)
      if (slotsError) console.error('copyShiftsToWeek roster_shifts backfill failed:', slotsError)
    }
  }

  revalidatePath('/manager/schedule')
  return { status: 'success', copiedCount, skippedCount }
}

export type AutoPlanErrorCode = 'errorNoShifts' | 'errorAlreadyPublished' | 'errorGeneric'

export type AutoPlanState = {
  status: 'idle' | 'success' | 'error'
  errorCode?: AutoPlanErrorCode
  filledSlots?: number
  totalSlots?: number
}

type ShiftTemplateRow = {
  id: string
  day_of_week: number
  start_time: string
  end_time: string
  shift_name: string
  capacity: number
  function_id: string
}

type AvailabilityRow = {
  employee_id: string
  day_of_week: number
  start_time: string
  end_time: string
  is_available: boolean
  is_all_day: boolean
}

const dayRank = new Map<number, number>(WEEK_DISPLAY_ORDER.map((day, index) => [day, index]))

function overlaps(aStart: string, aEnd: string, bStart: string, bEnd: string) {
  return aStart < bEnd && bStart < aEnd
}

export async function runAutoPlan(
  weekStartDate: string,
  _prevState: AutoPlanState,
  _formData: FormData
): Promise<AutoPlanState> {
  const supabase = await createClient()

  const [{ data: shifts }, { data: availability }, { data: employeeFunctions }, { data: employees }] =
    await Promise.all([
      supabase
        .from('shifts_template')
        .select('id, day_of_week, start_time, end_time, shift_name, capacity, function_id')
        .eq('week_start_date', weekStartDate)
        .returns<ShiftTemplateRow[]>(),
      supabase
        .from('availability')
        .select('employee_id, day_of_week, start_time, end_time, is_available, is_all_day')
        .eq('week_start_date', weekStartDate)
        .returns<AvailabilityRow[]>(),
      supabase.from('employee_functions').select('employee_id, function_id'),
      supabase.from('employees').select('id, full_name').order('full_name'),
    ])

  if (!shifts || shifts.length === 0) {
    return { status: 'error', errorCode: 'errorNoShifts' }
  }

  const { data: roster, error: rosterError } = await supabase
    .from('roster')
    .upsert({ week_start_date: weekStartDate }, { onConflict: 'week_start_date' })
    .select('id, is_published')
    .single()

  if (rosterError || !roster) {
    return { status: 'error', errorCode: 'errorGeneric' }
  }

  if (roster.is_published) {
    return { status: 'error', errorCode: 'errorAlreadyPublished' }
  }

  const functionsByEmployee = new Map<string, Set<string>>()
  for (const row of employeeFunctions ?? []) {
    if (!functionsByEmployee.has(row.employee_id)) {
      functionsByEmployee.set(row.employee_id, new Set())
    }
    functionsByEmployee.get(row.employee_id)!.add(row.function_id)
  }

  const availabilityByEmployeeDay = new Map<string, AvailabilityRow>()
  for (const row of availability ?? []) {
    availabilityByEmployeeDay.set(`${row.employee_id}-${row.day_of_week}`, row)
  }

  // Intervals each employee is already committed to this run, so we don't
  // double-book someone across overlapping shifts on the same day.
  const assignedIntervals = new Map<string, { start: string; end: string }[]>()

  const isEligible = (employeeId: string, shift: ShiftTemplateRow) => {
    if (!functionsByEmployee.get(employeeId)?.has(shift.function_id)) return false

    const avail = availabilityByEmployeeDay.get(`${employeeId}-${shift.day_of_week}`)
    if (!avail || !avail.is_available) return false
    if (!avail.is_all_day && (avail.start_time > shift.start_time || avail.end_time < shift.end_time)) {
      return false
    }

    const existing = assignedIntervals.get(`${employeeId}-${shift.day_of_week}`) ?? []
    return !existing.some((interval) =>
      overlaps(interval.start, interval.end, shift.start_time, shift.end_time)
    )
  }

  // Fill order, in priority order: day (Monday-first), then the shift's own
  // name, then start time, then id.
  //
  // Name outranks start time on purpose: the grid shows one row per shift
  // name within a function group, sorted by name (see page.tsx), so an
  // employee eligible for several rows should land in the topmost one —
  // "Baliemedewerker 01" before "02" before "03" — regardless of which of
  // those rows happens to start earliest. `numeric` makes "2" sort before
  // "10" rather than after it, for names that aren't zero-padded. The
  // trailing id compare is only there so the result is fully deterministic
  // instead of falling back on whatever order Postgres returned.
  const orderedShifts = [...shifts].sort((a, b) => {
    const dayDiff = (dayRank.get(a.day_of_week) ?? 0) - (dayRank.get(b.day_of_week) ?? 0)
    if (dayDiff !== 0) return dayDiff

    const nameDiff = a.shift_name.localeCompare(b.shift_name, undefined, { numeric: true })
    if (nameDiff !== 0) return nameDiff

    const timeDiff = a.start_time.localeCompare(b.start_time)
    if (timeDiff !== 0) return timeDiff

    return a.id.localeCompare(b.id)
  })

  const newRosterShifts: { roster_id: string; shift_template_id: string; employee_id: string | null }[] = []
  let filledSlots = 0
  let totalSlots = 0

  for (const shift of orderedShifts) {
    for (let slot = 0; slot < shift.capacity; slot++) {
      totalSlots++
      const employee = (employees ?? []).find((e) => isEligible(e.id, shift))

      if (employee) {
        const key = `${employee.id}-${shift.day_of_week}`
        const intervals = assignedIntervals.get(key) ?? []
        intervals.push({ start: shift.start_time, end: shift.end_time })
        assignedIntervals.set(key, intervals)
        filledSlots++
      }

      newRosterShifts.push({
        roster_id: roster.id,
        shift_template_id: shift.id,
        employee_id: employee?.id ?? null,
      })
    }
  }

  const { error: deleteError } = await supabase.from('roster_shifts').delete().eq('roster_id', roster.id)
  if (deleteError) {
    return { status: 'error', errorCode: 'errorGeneric' }
  }

  const { error: insertError } = await supabase.from('roster_shifts').insert(newRosterShifts)
  if (insertError) {
    return { status: 'error', errorCode: 'errorGeneric' }
  }

  revalidatePath('/manager/schedule')
  return { status: 'success', filledSlots, totalSlots }
}

export async function updateRosterShiftAssignment(rosterShiftId: string, employeeId: string | null) {
  const supabase = await createClient()

  const { data: rosterShift } = await supabase
    .from('roster_shifts')
    .select('roster_id')
    .eq('id', rosterShiftId)
    .maybeSingle()
  if (!rosterShift) return

  const { data: roster } = await supabase
    .from('roster')
    .select('is_published')
    .eq('id', rosterShift.roster_id)
    .maybeSingle()
  // Published rosters are locked — the UI already disables editing, this is
  // the server-side backstop.
  if (roster?.is_published) return

  await supabase.from('roster_shifts').update({ employee_id: employeeId }).eq('id', rosterShiftId)
  revalidatePath('/manager/schedule')
}

export type PublishResult = { status: 'success' } | { status: 'error' }

export async function publishRoster(rosterId: string): Promise<PublishResult> {
  const supabase = await createClient()
  const { error } = await supabase.from('roster').update({ is_published: true }).eq('id', rosterId)
  if (error) return { status: 'error' }

  revalidatePath('/manager/schedule')
  revalidatePath('/employee/schedule')
  return { status: 'success' }
}

export async function unpublishRoster(rosterId: string): Promise<PublishResult> {
  const supabase = await createClient()
  const { error } = await supabase.from('roster').update({ is_published: false }).eq('id', rosterId)
  if (error) return { status: 'error' }

  revalidatePath('/manager/schedule')
  revalidatePath('/employee/schedule')
  return { status: 'success' }
}
